# Generated by Django 5.0.3 on 2024-03-19 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionNom',
            fields=[
                ('emission_nom_id', models.AutoField(primary_key=True, serialize=False)),
                ('emission_nom_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emission_nom',
            },
        ),
        migrations.CreateModel(
            name='FuelTypes',
            fields=[
                ('fuel_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fuel_types',
            },
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vehicle_types',
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vin_no', models.CharField(max_length=17, unique=True)),
                ('registration_no', models.CharField(max_length=12, null=True)),
                ('address', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=16)),
                ('model_name', models.CharField(max_length=20)),
                ('engine_no', models.CharField(max_length=15)),
                ('making_date', models.DateField()),
                ('is_onboard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emission_nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_service.emissionnom')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_service.fueltypes')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_service.vehicletypes')),
            ],
            options={
                'db_table': 'vehicle_details',
            },
        ),
    ]
