# Generated by Django 5.0.3 on 2024-03-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='engine_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='registration_no',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
